#!/usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--relaxed','-r', action='store_true',
					help="Compiles the program without flags")
args = parser.parse_args()

relaxed = True if args.relaxed else False
strict_compile = "gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh"
simple_compile = "gcc *.c -o hsh"

if relaxed:
	subprocess.run(simple_compile, shell=True)
else:
	subprocess.run(strict_compile, shell=True)
